import { v4 as uuid } from 'uuid';

const notificationsData = [
	{
		id: uuid(),
		name: 'Woodie',
		avatar: '/assets/images/avatars/avatar_1.png',
		title: 'te etiqueto y a 18 personas mas en una publicación.',
		date: '30/07/2021',
		checked: false,
	},
	{
		id: uuid(),
		name: 'Felizio',
		avatar: '/assets/images/avatars/avatar_2.png',
		title: 'aprecio tu trabajo en una publicación.',
		date: '25/07/2021',
		checked: false,
	},
	{
		id: uuid(),
		name: 'Nickolai',
		avatar: '/assets/images/avatars/avatar_3.png',
		title: 'quiere conectar contigo.',
		date: '15/12/2021',
		checked: false,
	},
	{
		id: uuid(),
		name: 'Elsinore',
		avatar: '/assets/images/avatars/avatar_4.png',
		title: 'te envio un mensaje.',
		date: '11/07/2020',
		checked: true,
	},
	{
		id: uuid(),
		name: 'Harvey',
		avatar: '/assets/images/avatars/avatar_5.png',
		title: 'te agrego y a 18 personas a un grupo.',
		date: '29/01/2021',
		checked: true,
	},
	{
		id: uuid(),
		name: 'Othello',
		avatar: '/assets/images/avatars/avatar_6.png',
		title: 'te etiqueto y a 18 personas mas en una publicación.',
		date: '25/07/2021',
		checked: true,
	},
	{
		id: uuid(),
		name: 'Anselma',
		avatar: '/assets/images/avatars/avatar_7.png',
		title: 'te etiqueto y a 18 personas mas en una publicación.',
		date: '25/07/2021',
		checked: true,
	},
	{
		id: uuid(),
		name: 'Fredia',
		avatar: '/assets/images/avatars/avatar_8.png',
		title: 'te etiqueto y a 18 personas mas en una publicación.',
		date: '25/07/2021',
		checked: false,
	},
	{
		id: uuid(),
		name: 'Iseabal',
		avatar: '/assets/images/avatars/avatar_9.png',
		title: 'te etiqueto y a 18 personas mas en una publicación.',
		date: '25/07/2021',
		checked: false,
	},
	{
		id: uuid(),
		name: 'Chevy',
		avatar: '/assets/images/avatars/avatar_10.png',
		title: 'te etiqueto y a 18 personas mas en una publicación.',
		date: '25/07/2021',
		checked: true,
	},
	{
		id: uuid(),
		name: 'Nap',
		avatar: '/assets/images/avatars/avatar_11.png',
		title: 'te etiqueto y a 18 personas mas en una publicación.',
		date: '25/07/2021',
		checked: true,
	},
	{
		id: uuid(),
		name: 'Terza',
		avatar: '/assets/images/avatars/avatar_1.png',
		title: 'te etiqueto y a 18 personas mas en una publicación.',
		date: '25/07/2021',
		checked: true,
	},
	{
		id: uuid(),
		name: 'Nowell',
		avatar: '/assets/images/avatars/avatar_2.png',
		title: 'te etiqueto y a 18 personas mas en una publicación.',
		date: '25/07/2021',
		checked: false,
	},
	{
		id: uuid(),
		name: 'Nicol',
		avatar: '/assets/images/avatars/avatar_3.png',
		title: 'te etiqueto y a 18 personas mas en una publicación.',
		date: '25/07/2021',
		checked: false,
	},
	{
		id: uuid(),
		name: 'Lianna',
		avatar: '/assets/images/avatars/avatar_4.png',
		title: 'te etiqueto y a 18 personas mas en una publicación.',
		date: '25/07/2021',
		checked: false,
	},
	{
		id: uuid(),
		name: 'Georas',
		avatar: '/assets/images/avatars/avatar_4.png',
		title: 'te etiqueto y a 18 personas mas en una publicación.',
		date: '25/07/2021',
		checked: false,
	},
	{
		id: uuid(),
		name: 'Obed',
		avatar: '/assets/images/avatars/avatar_5.png',
		title: 'te etiqueto y a 18 personas mas en una publicación.',
		date: '25/07/2021',
		checked: false,
	},
	{
		id: uuid(),
		name: 'Gale',
		avatar: '/assets/images/avatars/avatar_6.png',
		title: 'te etiqueto y a 18 personas mas en una publicación.',
		date: '25/07/2021',
		checked: false,
	},
	{
		id: uuid(),
		name: 'Raddie',
		avatar: '/assets/images/avatars/avatar_7.png',
		title: 'te etiqueto y a 18 personas mas en una publicación.',
		date: '25/07/2021',
		checked: false,
	},
	{
		id: uuid(),
		name: 'Theodosia',
		avatar: '/assets/images/avatars/avatar_8.png',
		title: 'te etiqueto y a 18 personas mas en una publicación.',
		date: '25/07/2021',
		checked: false,
	},
];

export default notificationsData;
